language: node_js
node_js:
  - "6"
  - "7"
  - "8"

os:
  - linux
  - osx

matrix:
  include:
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew install gcc5 && CC=gcc-5 && CXX=g++-5"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g+5"

before_install:
    - eval "${MATRIX_EVAL}"