language: node_js

node_js:
  - "6"
  - "7"
  - "8"

os:
  - linux
  - osx

env:
  - CXX=g++-5
    
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update         ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc@5  ; fi      

 