os:
  - Visual Studio 2015
  - Visual Studio 2017

environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "7"
    - nodejs_version: "6"

platform:
  - x86
  - x64

init:
  - ps: IF ($env:APPVEYOR_REPO_BRANCH -eq "develop") {$env:APPVEYOR_CACHE_SKIP_RESTORE = "true"}
  - ps: IF ($env:APPVEYOR_REPO_BRANCH -eq "develop") {$env:APPVEYOR_CACHE_SKIP_SAVE = "true"}

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - git submodule update --init --recursive
  - npm config set spin false
  - npm i -g npm node-gyp --production
  - npm install

# cache:
#   - '%APPDATA%\npm-cache'

test_script:
  - npm test

matrix:
  fast_finish: true

# build: off