os:
  - Visual Studio 2015
  - Visual Studio 2017

environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "7"
    - nodejs_version: "6"

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - git submodule update --init --recursive
  - npm config set spin false
  - npm i -g npm node-gyp --production
  - npm install

cache:
  - '%APPDATA%\npm-cache'

test_script:
  - npm test

matrix:
  fast_finish: true

# build: off